trigger: none

parameters:
- name: arch
  type: string
  values:
  - amd64
  default: amd64

- name: pool
  type: string
  values:
  - sonicbld
  - sonicbld-armhf
  - sonicbld-arm64
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string
  default: sonic-slave-bullseye

variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(Build.SourceBranchName)
    ${{ else }}:
      value: $(Build.SourceBranchName)

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  always: true
  branches:
    include:
    - master

jobs:
- job: build
  timeoutInMinutes: 240
  pool:
    vmImage: 'ubuntu-20.04'
  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest

  steps:
    - checkout: none
    - script: |
        sudo apt-get update
        sudo apt-get install -qq -y \
        libhiredis-dev \
        libnl-3-dev \
        libnl-genl-3-dev \
        libnl-route-3-dev \
        libnl-nf-3-dev \
        swig

        sudo apt-get install libsasl2-dev
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install libssl-dev
        sudo apt-get install libssl1.0.0
        sudo apt-get install gcc g++ libboost-dev cmake zlib1g-dev libsasl2-2

        git clone https://github.com/jbeder/yaml-cpp.git
        cd yaml-cpp
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=OFF ..
        make
        sudo make install
        cd ../../

        git clone https://github.com/sonic-net/sonic-swss-common.git
        sudo apt-get install make libtool m4 autoconf dh-exec debhelper cmake pkg-config nlohmann-json3-dev \
                    libhiredis-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev \
                    libnl-nf-3-dev swig3.0 libpython2.7-dev libpython3-dev \
                    libgtest-dev libgmock-dev libboost-serialization-dev uuid-dev libzmq5 libzmq3-dev
        sudo apt-get install -y redis-server redis-tools
        sudo apt-get install -y python3-pip
        sudo pip3 install pytest
        sudo apt-get install -y python
        sudo apt-get install -y libyang-dev
        ARCH=$(dpkg --print-architecture)
        set -x
        sudo curl -fsSL -o /usr/local/bin/bazel \
            https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${ARCH}
        sudo chmod 755 /usr/local/bin/bazel
        cd sonic-swss-common
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo mkdir -p /usr/local/include/sonic-swss-common/common
        sudo cp common/*.h /usr/local/include/sonic-swss-common/common
        cd ../

        git clone https://github.com/FengPan-Frank/sonic-bmp.git
        cd sonic-bmp
        git checkout $(BUILD_BRANCH)
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../  
        make
        ldconfig -p | grep libsasl2
